### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by wojtmic** [MHeMoTexHuK/new-console#4]
No build Button, h e l p .

**Comment by Mnemotechnician** [comment]
????????????????
what do you even mean

can you  **e l a b o r a t e**?

**Comment by wojtmic** [comment]
Cant find run workflow button. I just want to get a v7 build.

**Comment by wojtmic** [comment]
Or just tell me how to make it work with 126.2

**Comment by Mnemotechnician** [comment]
1. 126.2 is v6 and newconsole is incompatible with it
2. the use the [actions tab](https://github.com/Mnemotechnician/new-console/actions) if you actually want to get the latest build, which is compatible with 136
3. if you're actually on v7, you can use the in-game releases browser to download the latest pre-release, which will be created in a minute

**Comment by Mnemotechnician** [comment]
4. if this is somehow not what you mean, consider __**elaborating**__. I'm not a wizard and I can't read your mind to understand what you mean by creating an issue whose description is 4 words long
